### ISSUE TITLE
Tidy up configuration

### ISSUE THREAD

**Issue by ace-subido** [bloom-solutions/stellar_base-rails#57]
**Problem**
Right now, it's hard to make sure if you've configured it right. The docs are verbose enough to provide this guidance, but the configuration should be readable enough to make it easier to use.

**Proposal**
```
StellarBase.configure = Rails.root.join("config", "stellar_base.yml")
# We can also provide something like 
# StellarBase.validate_config_file = Rails.root.join("config", "stellar_base.yml")

# config/stellar_base.yml

horizon_url:
stellar_network: "public"
sending_strategy:

sep_0001:
  TRANSFER_SERVER:
  ASSET_ISSUER:
sep_0006:
  enable_fees_endpoint: true
  
  # if present /withdraw is automatically enabled
  depositable_assets:
    - asset_code: BTCT
      fee_fixed_from: Withdraw::Bitcoins::
  
  # if present /withdraw is automatically enabled
  withdrawable_assets:
    - asset_code: BTCT
      fee_fixed_from
bridge_server:
  on_bridge_callback: BridgeCallback::Process

  # if enabled, it will verify the payload with the mac key
  enable_verify_mac_payload: true
  bridge_callbacks_mac_key:

  # compares the callback POST'd if it exists in the XLM blockchain
  enable_authenticity_check:
account_subscriptions:
  subscribe_to:
    -
```

rails c
> StellarBase::ValidateConfig.()
